### ISSUE TITLE
Cannot access the questions and answers.

### ISSUE THREAD

**Issue by maxwellyin** [Maluuba/newsqa#41] opened 2022-07-06 14:22 UTC
The link - download the tar.gz file for the questions and answers from [here](https://msropendata.com/datasets/939b1042-6402-4697-9c15-7a28de7e1321) - does not work. The dataset seems to be loading forever.
![image](https://user-images.githubusercontent.com/20868903/177572835-54f20fb9-6d35-4ba8-ab49-7eeaa065bf91.png)

**Comment by maxwellyin** [comment] 2022-07-06 14:25
I wait for about half an hour and it's still loading.

**Comment by juharris** [comment] 2022-07-06 15:00
Do you see the login option on the left of the page? It loads for me even when not logged in, but maybe logging in can help?

**Comment by maxwellyin** [comment] 2022-07-06 15:06
I've already login. I'm from Canada. Is there anything like regional restrictions?
![image](https://user-images.githubusercontent.com/20868903/177582535-a8d9a5a0-f35a-4c19-8edb-f27f5a2adc14.png)

**Comment by juharris** [comment] 2022-07-06 15:08
I'm not sure if there are regional restrictions, but I'm in Canada too and it's fine for me. Maybe try in another browser or private/incognito tab?

**Comment by maxwellyin** [comment] 2022-07-06 15:34
Solved. I changed from Edge to Chrome and it worked. It's a pity that the Microsoft website doesn't support their own browser:)

Thanks for your help!

**Comment by juharris** [comment] 2022-07-06 15:41
That's weird cause I'm using Edge. Maybe you have something bad cached. I'm glad you got it working. I'll close this since you got it working and I can't reproduce it.

**Closed as completed by juharris** 2022-07-06 15:41 UTC
